(defun acquire_elpa_packages (package_list)
  (cl-loop for package_name in package_list do
           (ignore-errors (install_if_missing package_name))
           )
  )

(defun install_if_missing (package_name)
  (when (not (package-installed-p package_name))
    (update_packages_if_neccessary)
    (message "Installing package %s..." package_name)
    (package-install package_name)
    (message "Installing package %s... done" package_name)
    )
  )

(defun update_packages_if_neccessary ()
  (when (not (boundp 'elpa_update_check))
    (setq elpa_update_check t)
    (package-refresh-contents)
    )
  )
